import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import Navbar from '@/components/Navbar';
import LaunchButton from '@/components/LaunchButton';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lab 10 Coello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900 min-h-screen flex flex-col`}
      >
        <Navbar />

        <main className="flex-grow container mx-auto px-4 py-10">
          {children}
        </main>

        <footer className="w-full py-20 flex justify-center">
          <LaunchButton />
        </footer>
      </body>
    </html>
  );
}
